"""
Person 1 -- Clickbait Detection.
Auto-generated by Copy_of_NTI_AI_HeadlineClickbait_.ipynb.
Do not hand-edit this file -- re-run that notebook's export cell instead, or edits here
will just be silently overwritten and the two will drift apart again.
"""
import re
import emoji
import requests
import trafilatura
import torch
from newspaper import Article
from bs4 import BeautifulSoup
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Named clickbait_model / clickbait_tokenizer (not model / tokenizer) so this doesn't
# collide with Person 2's globally-named `model` when both are imported into the same
# notebook (see Notebook 3, Section 9 for why that collision mattered).
clickbait_tokenizer = AutoTokenizer.from_pretrained("models/clickbait_model")
clickbait_model = AutoModelForSequenceClassification.from_pretrained("models/clickbait_model")

HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}


def dedupe_emojis(text):
    result = []
    prev = None
    for ch in text:
        if ch in emoji.EMOJI_DATA and ch == prev:
            continue
        result.append(ch)
        prev = ch
    return "".join(result)


def caps_ratio(text):
    letters = [c for c in text if c.isalpha()]
    if not letters:
        return 0.0
    return sum(1 for c in letters if c.isupper()) / len(letters)


def clean_headline(text):
    text = re.sub(r"http\S+", "", text)
    text = dedupe_emojis(text)
    text = emoji.demojize(text, delimiters=(" ", " "))
    text = text.replace("_", " ")
    text = re.sub(r"[#@]\w+", "", text)
    text = (text.replace("\u2019", "'").replace("\u2018", "'")
                .replace("\u201c", '"').replace("\u201d", '"')
                .replace("\u2014", "-").replace("\u2013", "-")
                .replace("\u2026", "..."))
    text = re.sub(r"[\u200b\u200c\u200d\ufeff\ufe0f\u20e3]", "", text)
    text = re.sub(r"[\u25a0\u2022]", "", text)
    text = "".join(chr(ord(c) - 0xFEE0) if 0xFF01 <= ord(c) <= 0xFF5E else c for c in text)
    text = re.sub(r"[\u1D00-\u1D7F\u1D80-\u1DBF\u2070-\u209F]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def predict_clickbait(headline):
    inputs = clickbait_tokenizer(headline, return_tensors="pt", truncation=True, padding=True, max_length=64)
    inputs = {k: v.to(clickbait_model.device) for k, v in inputs.items()}
    with torch.no_grad():
        outputs = clickbait_model(**inputs)
    probs = torch.softmax(outputs.logits, dim=-1)
    pred = probs.argmax().item()
    return ("clickbait" if pred == 1 else "not clickbait"), probs[0][pred].item()


def _try_newspaper(url):
    article = Article(url)
    article.download()
    article.parse()
    return article.title.strip(), article.text.strip()


def _try_trafilatura(url):
    downloaded = trafilatura.fetch_url(url)
    text = trafilatura.extract(downloaded, include_comments=False, favor_recall=True)
    metadata = trafilatura.extract_metadata(downloaded)
    title = metadata.title.strip() if metadata and metadata.title else ""
    text = (text or "").strip()
    paras = text.split("\n")
    deduped = [p for i, p in enumerate(paras) if i == 0 or p != paras[i - 1]]
    text = "\n".join(deduped)
    return title, text


def _try_bs4(url):
    resp = requests.get(url, headers=HEADERS, timeout=10)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.content, "html.parser")
    og_title = soup.find("meta", property="og:title")
    if og_title and og_title.get("content"):
        title = og_title["content"].strip()
    else:
        title_tag = soup.find("title")
        title = title_tag.get_text().strip() if title_tag else ""

    # Remove nav/sidebar/related-content blocks BEFORE collecting <p> tags, so
    # their teaser blurbs ("Learn more about...", "Six actions to...") can't
    # leak into the article body and pollute downstream clickbait/verification.
    NOISE_SELECTORS = [
        "nav", "aside", "footer", "header",
        '[class*="related"]', '[id*="related"]',
        '[class*="sidebar"]', '[id*="sidebar"]',
        '[class*="widget"]', '[id*="widget"]',
        '[class*="recommend"]', '[class*="promo"]',
        '[class*="newsletter"]', '[class*="share"]',
        '[class*="comment"]', '[class*="trending"]',
        '[class*="also-read"]', '[class*="read-more"]',
    ]
    for sel in NOISE_SELECTORS:
        for tag in soup.select(sel):
            tag.decompose()

    container = soup.find("article") or soup.find("main")
    if container is None:
        container = soup.find(attrs={"class": re.compile(r"(article|post)[-_]?(body|content)", re.I)}) \
            or soup.find(attrs={"id": re.compile(r"(article|post)[-_]?(body|content)", re.I)})
    scope = container if container else soup

    paragraphs = [p.get_text().strip() for p in scope.find_all("p")]
    body = " ".join(p for p in paragraphs if len(p) > 40)
    return title, body


def _headline_quality(headline):
    """Higher = more likely a real journalistic headline, not a generic HTML
    page title. Catches short institutional titles like "Climate change" or
    "Evidence - NASA Science" before they reach the clickbait/verification
    models, which were trained on real headline text."""
    if not headline:
        return -99
    words = headline.split()
    score = min(len(words), 12)
    if len(words) < 4:
        score -= 8
    if re.search(r"\s[-|]\s", headline) and len(words) < 8:
        score -= 4
    return score


def _strip_boilerplate(text):
    if not text:
        return text
    markers = ["unsubscribe", "privacy policy", "spam thing", "your email address is safe"]

    def clean_line(line):
        sentences = re.split(r'(?<=[.!?])\s+', line)
        kept = [s for s in sentences if not any(m in s.lower() for m in markers)]
        return " ".join(kept).strip()

    lines = [clean_line(line) for line in text.split("\n")]
    lines = [l for l in lines if l]
    return "\n".join(lines).strip()


def extract_article(url):
    """Body and headline are scored and picked independently: body still goes
    to whichever method returned the most complete text, but headline goes to
    whichever method's title actually looks like a real headline (see
    _headline_quality). The two winners can come from different methods --
    that's the fix for "long article body drags along a bad page-title
    headline"."""
    methods = [
        ("trafilatura", _try_trafilatura),
        ("newspaper3k", _try_newspaper),
        ("bs4_fallback", _try_bs4),
    ]
    candidates = []
    for method_name, method_fn in methods:
        try:
            headline, body_text = method_fn(url)
            body_text = _strip_boilerplate(body_text)
            if headline and body_text and len(body_text) > 100:
                candidates.append({
                    "method": method_name,
                    "headline": headline,
                    "article_text": body_text,
                    "headline_score": _headline_quality(headline),
                })
        except Exception:
            continue
    if not candidates:
        return {"success": False, "method": None, "headline": None, "article_text": None,
                "error": "Could not extract readable article content from this URL"}
    best_body = max(candidates, key=lambda c: len(c["article_text"]))
    best_headline = max(candidates, key=lambda c: c["headline_score"])
    return {
        "success": True,
        "method": best_body["method"],
        "headline_method": best_headline["method"],
        "headline": best_headline["headline"],
        "article_text": best_body["article_text"],
        "headline_quality_flag": "low" if best_headline["headline_score"] < 0 else "ok",
    }


def analyze_url(url):
    result = extract_article(url)
    if not result["success"]:
        return result
    cleaned_headline = clean_headline(result["headline"])
    label, confidence = predict_clickbait(cleaned_headline)
    result["cleaned_headline"] = cleaned_headline
    result["clickbait_label"] = label
    result["clickbait_score"] = round(confidence, 4)
    return result
