"""
Person 2 -- Headline/Article Verification.
Auto-generated by TruthLens_Headline_Verification.ipynb, Section 13.
Do not hand-edit this file -- re-run that notebook's export cell instead, or edits here
will just be silently overwritten and the two will drift apart again.
"""
import re
import numpy as np
import pandas as pd
import joblib
from sklearn.metrics.pairwise import cosine_similarity

REFUTING_WORDS = {
    "fake", "fraud", "hoax", "false", "deny", "denies", "denied", "not",
    "despite", "nope", "doubt", "doubts", "bogus", "debunk", "retract",
    "refute", "refuted", "no",
}

model = joblib.load("models/stance_model.joblib")
vectorizer = joblib.load("models/tfidf_vectorizer.joblib")
scaler = joblib.load("models/feature_scaler.joblib")

NLI_MODEL_NAME = "cross-encoder/nli-deberta-v3-base"
RELATEDNESS_MODEL_NAME = "all-MiniLM-L6-v2"
# Embedding-cosine-similarity threshold below which a pair is treated as off-topic
# (Sentence-BERT scale, not the old TF-IDF scale -- see Section 10.5).
RELATEDNESS_THRESHOLD = 0.15
_NLI_RAW_LABELS = ["Contradicted", "Discussed", "Supported"]

# USE_NLI defaults to True and load_nli() is called automatically below, at
# import time -- unlike the previous version of this file, which defaulted to
# False and required the caller to remember to enable NLI manually. That's why
# every report used to be generated by the weaker TF-IDF path regardless of
# what was enabled interactively in the source notebook.
USE_NLI = False
nli_tokenizer = None
nli_model = None
relatedness_embedder = None
DEVICE = "cpu"


def load_nli():
    """Load the NLI model and the Sentence-BERT relatedness embedder, and turn
    on the NLI path. Safe to call again (e.g. to retry after a failed
    auto-load, or to switch devices)."""
    global nli_tokenizer, nli_model, relatedness_embedder, USE_NLI, DEVICE
    import torch
    from transformers import AutoTokenizer, AutoModelForSequenceClassification
    from sentence_transformers import SentenceTransformer

    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    nli_tokenizer = AutoTokenizer.from_pretrained(NLI_MODEL_NAME)
    nli_model = AutoModelForSequenceClassification.from_pretrained(NLI_MODEL_NAME).to(DEVICE)
    nli_model.eval()
    relatedness_embedder = SentenceTransformer(RELATEDNESS_MODEL_NAME, device=DEVICE)
    USE_NLI = True


try:
    load_nli()
except Exception as _e:  # e.g. no internet / model download blocked
    print(f"[person2_verification] Could not auto-load NLI/embedding models ({_e}); "
          f"falling back to the TF-IDF path (USE_NLI=False). Call load_nli() to retry.")


def clean_text(text):
    """Lowercase, strip punctuation/numbers noise, collapse whitespace."""
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def word_overlap(headline, body):
    h_words, b_words = set(headline.split()), set(body.split())
    if not h_words or not b_words:
        return 0.0
    return len(h_words & b_words) / len(h_words | b_words)


def refuting_count(headline):
    return sum(1 for w in headline.split() if w in REFUTING_WORDS)


def build_features(df):
    h_vec = vectorizer.transform(df["clean_headline"])
    b_vec = vectorizer.transform(df["clean_body"])
    dot = np.array(h_vec.multiply(b_vec).sum(axis=1)).flatten()
    h_norm = np.sqrt(np.array(h_vec.multiply(h_vec).sum(axis=1)).flatten())
    b_norm = np.sqrt(np.array(b_vec.multiply(b_vec).sum(axis=1)).flatten())
    cos_sim = dot / (h_norm * b_norm + 1e-8)
    overlap = df.apply(lambda r: word_overlap(r["clean_headline"], r["clean_body"]), axis=1).values
    refute = df["clean_headline"].apply(refuting_count).values
    h_len = df["clean_headline"].apply(lambda x: len(x.split())).values
    b_len = df["clean_body"].apply(lambda x: len(x.split())).values
    return np.column_stack([cos_sim, overlap, refute, h_len, b_len])


def split_sentences(text):
    text = str(text).replace("\n", " ")
    sentences = re.split(r"(?<=[.!?])\s+", text)
    return [s.strip() for s in sentences if len(s.strip().split()) >= 4]


def extract_evidence(headline, body, top_k=3):
    """Rank article sentences by similarity to the headline. Uses the
    Sentence-BERT embedder when loaded (generalizes across vocabulary), falls
    back to the FNC-1-only TF-IDF vectorizer otherwise."""
    sentences = split_sentences(body)
    if not sentences:
        return []

    if relatedness_embedder is not None:
        from sentence_transformers import util as st_util
        h_emb = relatedness_embedder.encode(headline, convert_to_tensor=True)
        s_embs = relatedness_embedder.encode(sentences, convert_to_tensor=True)
        sims = st_util.cos_sim(h_emb, s_embs).flatten().tolist()
    else:
        clean_h = clean_text(headline)
        clean_sents = [clean_text(s) for s in sentences]
        h_vec = vectorizer.transform([clean_h])
        s_vecs = vectorizer.transform(clean_sents)
        sims = cosine_similarity(h_vec, s_vecs).flatten().tolist()

    ranked_idx = sorted(range(len(sims)), key=lambda i: sims[i], reverse=True)[:top_k]
    return [(sentences[i], round(float(sims[i]), 3)) for i in ranked_idx]


def embedding_relatedness(headline, body):
    """Semantic relatedness between headline and body via Sentence-BERT cosine
    similarity -- replaces the old TF-IDF relatedness gate, which produced a
    near-zero score (and a false "Unrelated" verdict) on any article outside
    FNC-1's news vocabulary."""
    h_emb = relatedness_embedder.encode(headline, convert_to_tensor=True)
    b_emb = relatedness_embedder.encode(body[:2000], convert_to_tensor=True)
    from sentence_transformers import util as st_util
    return float(st_util.cos_sim(h_emb, b_emb).item())


def nli_stance(headline, body):
    relatedness_score = embedding_relatedness(headline, body)

    if relatedness_score < RELATEDNESS_THRESHOLD:
        return ("Unrelated",
                {"Unrelated": 1.0, "Supported": 0.0, "Contradicted": 0.0, "Discussed": 0.0},
                relatedness_score)

    import torch
    inputs = nli_tokenizer(body, headline, return_tensors="pt", truncation=True, max_length=512).to(DEVICE)
    with torch.no_grad():
        logits = nli_model(**inputs).logits
    probs = torch.softmax(logits, dim=1)[0]
    proba = dict(zip(_NLI_RAW_LABELS, [round(p, 3) for p in probs.tolist()]))
    proba["Unrelated"] = 0.0
    label = max(proba, key=proba.get)
    return label, proba, relatedness_score


def build_user_notice(stance, proba):
    if stance == "Supported":
        return {"match": True, "message": "This headline appears to be supported by the article content."}
    elif stance == "Contradicted":
        return {"match": False, "message": (
            "\u26a0\ufe0f Warning: This headline appears to CONTRADICT the article content. "
            "The headline may be misleading, inaccurate, or reworded to say the opposite of "
            "what the article actually reports. Please read the full article before trusting "
            "the headline.")}
    elif stance == "Discussed":
        return {"match": True, "message": (
            "\u2139\ufe0f Notice: The article discusses this topic but doesn't explicitly confirm "
            "or deny the headline's specific claim. Read the article for the full context "
            "before drawing conclusions from the headline alone.")}
    else:
        return {"match": False, "message": (
            "\u26a0\ufe0f Notice: This article does not appear to be about what the headline "
            "claims -- the content looks unrelated to the headline's topic. Treat the headline "
            "with caution and check the article body yourself.")}


def verify_headline(headline, body, top_k_evidence=3):
    if USE_NLI:
        label, proba, relatedness_score = nli_stance(headline, body)
    else:
        row = pd.DataFrame([{"clean_headline": clean_text(headline), "clean_body": clean_text(body)}])
        features = build_features(row)
        features_scaled = scaler.transform(features)
        relatedness_score = float(features[0][0])
        label = model.predict(features_scaled)[0]
        proba = dict(zip(model.classes_, model.predict_proba(features_scaled)[0].round(3)))

    evidence = extract_evidence(headline, body, top_k=top_k_evidence)
    notice = build_user_notice(label, proba)
    return {
        "headline": headline, "stance": label, "confidence": proba,
        "evidence": evidence, "match": notice["match"], "user_message": notice["message"],
        "relatedness_score": round(relatedness_score, 3), "used_nli": USE_NLI,
    }
